Uncaught exception
Traceback (most recent call last):
  File "/home/francesco/Desktop/TESI/Schedulers/validate.py", line 140, in <module>
    main()
  File "/home/francesco/Desktop/TESI/Schedulers/validate.py", line 135, in main
    d = tiling(a, b, c)
  File "/home/francesco/Desktop/TESI/Schedulers/validate.py", line 111, in tiling
    CTAs = scheduler.scheduler_algorithm(a, b, c)
  File "/home/francesco/Desktop/TESI/Schedulers/Schedulers/TwoLevelRoundRobin.py", line 88, in scheduler_algorithm
    self.printing_csv()
  File "/home/francesco/Desktop/TESI/Schedulers/Schedulers/TwoLevelRoundRobin.py", line 149, in printing_csv
    row.append(str(self.__scheduler_info[CTA][CTA]["x"]))
KeyError: 0
